name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get install -y libx11-dev
        sudo apt-get install -y libxext-dev
        sudo apt-get install -y libxft-dev
        sudo apt-get install -y libxinerama-dev
        sudo apt-get install -y libxcursor-dev
        sudo apt-get install -y libxrender-dev
        sudo apt-get install -y libxfixes-dev
        sudo apt-get install -y libpango1.0-dev
        sudo apt-get install -y libgl1-mesa-dev
        sudo apt-get install -y libglu1-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
